#![allow(clippy::assign_op_pattern)] // generated by SmallFpConfig derive macro
use crate::error::WARPError;
use crate::traits::AccumulationScheme;
use crate::types::{
    AccumulatorInstance, AccumulatorWitness, ProveResult, WARPParams, WARPProof, WARPProverKey,
    WARPVerifierKey,
};
use ark_codes::traits::LinearCode;
use ark_ff::{Field, PrimeField};
use ark_mt::MerkleHasher;
use ark_poly::{DenseMultilinearExtension, Polynomial};
use ark_std::log2;
use config::WARPConfig;
use effsc::hypercube::compute_hypercube_eq_evals;
use protocol::transcript::{absorb_instances, parse_statement};
use relations::{r1cs::R1CSConstraints, BundledPESAT};
use spongefish::{Decoding, Encoding, NargDeserialize, NargSerialize, ProverState, VerifierState};
use std::marker::PhantomData;
use utils::scale_and_sum;
use utils::concat_slices;

pub mod config;
pub mod constraints;
pub mod crypto;
pub mod error;
pub mod params;
pub mod profile;
pub mod protocol;
pub mod relations;
pub mod serialize;
pub mod traits;
pub mod types;
pub mod utils;

/// Re-exports the handful of items every WARP consumer needs. Use as
/// `use warp::prelude::*;`.
pub mod prelude {
    pub use crate::config::WARPConfig;
    pub use crate::error::{DeciderError, ProverError, VerifierError, WARPError};
    pub use crate::traits::AccumulationScheme;
    pub use crate::types::{
        AccumulatorEntry, AccumulatorInstance, AccumulatorWitness, AccumulatorWitnessEntry,
        WARPProof, WARPProverKey, WARPVerifierKey,
    };
    pub use crate::WARP;
}

use crate::crypto::merkle::warp_scheme;
use error::{DeciderError, ProverError, VerifierError};
use protocol::iors::{
    batching::{
        Batching, BatchingProverCarry, BatchingProverInput, BatchingProverOutput, BatchingReduced,
        BatchingVerifierInput, BatchingVerifierOutput,
    },
    bridge::{
        Bridge, BridgeProverCarry, BridgeProverInput, BridgeProverOutput, BridgeReduced,
        BridgeVerifierInput, BridgeVerifierOutput,
    },
    ood::{Ood, OodProverInput, OodProverOutput, OodReduced, OodVerifierInput, OodVerifierOutput},
    pesat::{
        Pesat, PesatProverCarry, PesatProverInput, PesatProverOutput, PesatReduced,
        PesatVerifierCarry, PesatVerifierInput, PesatVerifierOutput,
    },
    proximity::{
        Proximity, ProximityProof, ProximityProverInput, ProximityProverOutput,
        ProximityVerifierInput, ProximityVerifierOutput,
    },
    sample_queries::{
        SampleQueries, SampleQueriesProverInput, SampleQueriesProverOutput, SampleQueriesReduced,
        SampleQueriesVerifierInput, SampleQueriesVerifierOutput,
    },
    twin_constraint::{
        TwinConstraint, TwinConstraintProverCarry, TwinConstraintProverInput,
        TwinConstraintProverOutput, TwinConstraintReduced, TwinConstraintVerifierInput,
        TwinConstraintVerifierOutput,
    },
    IOR,
};

pub struct WARP<F: Field, P: BundledPESAT<F>, C: LinearCode<F> + Clone, H: MerkleHasher> {
    pub params: WARPParams<F, P, C, H>,
}

impl<F, P, C, H> WARP<F, P, C, H>
where
    F: Field,
    P: Clone + BundledPESAT<F, Config = (usize, usize, usize)>,
    C: LinearCode<F> + Clone,
    H: MerkleHasher<Symbol = Vec<F>>,
{
    pub fn new(config: WARPConfig<F, P>, code: C, p: P, hasher: H) -> WARP<F, P, C, H> {
        Self {
            params: WARPParams {
                _f: PhantomData,
                config,
                code,
                p,
                hasher,
            },
        }
    }
}

impl<F, P, C, H> AccumulationScheme<F, H> for WARP<F, P, C, H>
where
    F: Field + PrimeField + Encoding<[u8]> + Decoding<[u8]> + NargDeserialize + NargSerialize,
    P: Clone + BundledPESAT<F, Constraints = R1CSConstraints<F>, Config = (usize, usize, usize)>,
    C: LinearCode<F> + Clone,
    H: MerkleHasher<Symbol = Vec<F>>,
    H::Digest: Encoding<[u8]> + Decoding<[u8]> + NargSerialize + NargDeserialize + Clone + Eq,
{
    type Index = P;
    type ProverKey = WARPProverKey<P>;
    type VerifierKey = WARPVerifierKey;
    type Instances = Vec<Vec<F>>;
    type Witnesses = Vec<Vec<F>>;

    fn index(
        prover_state: &mut ProverState,
        index: Self::Index,
    ) -> spongefish::VerificationResult<(Self::ProverKey, Self::VerifierKey)> {
        let (m, n, k) = index.config();
        prover_state.public_message(&index.description());
        prover_state.prover_message(&F::from(m as u32));
        prover_state.prover_message(&F::from(n as u32));
        prover_state.prover_message(&F::from(k as u32));
        Ok((
            WARPProverKey {
                index,
                m,
                n,
                k,
            },
            WARPVerifierKey { m, n, k },
        ))
    }

    #[tracing::instrument(name = "warp.prove", skip_all)]
    fn prove(
        &self,
        pk: Self::ProverKey,
        prover_state: &mut ProverState,
        witnesses: Self::Witnesses,
        instances: Self::Instances,
        acc_instance: AccumulatorInstance<F, H>,
        acc_witness: AccumulatorWitness<F, H>,
    ) -> ProveResult<F, H> {
        if instances.len() < 2 {
            return Err(ProverError::InsufficientInstances {
                got: instances.len(),
            });
        }
        if witnesses.len() != instances.len() {
            return Err(ProverError::InstanceWitnessLengthMismatch {
                instances: instances.len(),
                witnesses: witnesses.len(),
            });
        }
        if acc_witness.td.len() != acc_instance.rt.len() {
            return Err(ProverError::AccumulatorShapeMismatch {
                instances: acc_instance.rt.len(),
                roots: acc_witness.td.len(),
            });
        }

        let (l1, l) = (self.params.config.l1, self.params.config.l);
        let l2 = l - l1;
        if !l.is_power_of_two() {
            return Err(ProverError::ConfigParameterInvalid {
                reason: format!("config.l = {l} is not a power of two"),
            });
        }

        #[allow(non_snake_case)]
        let (M, N, k) = (pk.m, pk.n, pk.k);
        let (log_m, log_l) = (log2(M) as usize, log2(l) as usize);
        let n = self.params.code.code_len();
        let log_n = log2(n) as usize;

        if instances[0].len() != N - k {
            return Err(ProverError::InstanceLengthMismatch {
                expected: N - k,
                got: instances[0].len(),
            });
        }
        absorb_instances(prover_state, &instances);
        acc_instance.absorb_into(prover_state);

        // Destructure acc_witness. Codewords live inside td[i].codewords();
        // we extract the single codeword per accumulator entry into acc_fs
        // for use by twin_constraint.
        let AccumulatorWitness {
            td: acc_tds,
            w: acc_ws,
        } = acc_witness;
        let acc_fs: Vec<Vec<F>> = acc_tds.iter().map(|td| td.codewords()[0].clone()).collect();

        // IOR instances (stateless or borrowing &self.params for the &self lifetime).
        let pesat_ior = Pesat::<F, C, H> {
            code: &self.params.code,
            hasher: &self.params.hasher,
            _phantom: PhantomData,
        };
        let twin_constraint_ior = TwinConstraint::<F, H> {
            r1cs: self.params.p.constraints(),
            _phantom: PhantomData,
        };
        let bridge_ior = Bridge::<F, P, H>::new();
        let ood_ior = Ood::<F>::new();
        let sample_queries_ior = SampleQueries::<F>::new();
        let batching_ior = Batching::<F>::new();
        let proximity_ior = Proximity::<F, H> {
            hasher: &self.params.hasher,
            _phantom: PhantomData,
        };

        // ── IOR 1: PESAT — encode witnesses, commit, derive τ ────────
        let PesatProverOutput {
            reduced: PesatReduced { mus, taus },
            carry: PesatProverCarry { codewords, td_0 },
        } = pesat_ior.prove(
            prover_state,
            PesatProverInput {
                l1,
                log_m,
                witnesses: &witnesses,
            },
        )?;

        // ── IOR 2: TwinConstraint — fused-fold sumcheck ──────────────
        let TwinConstraintProverOutput {
            reduced:
                TwinConstraintReduced {
                    gamma: _,
                    zeta_0,
                    beta_tau,
                    deferred: _,
                },
            carry: TwinConstraintProverCarry { f, z },
        } = twin_constraint_ior.prove(
            prover_state,
            TwinConstraintProverInput {
                acc_instance,
                l1_mus: &mus,
                l1_taus: &taus,
                witnesses: &witnesses,
                instances: &instances,
                acc_witness_w: &acc_ws,
                fresh_codewords: &codewords,
                acc_codewords: &acc_fs,
                log_l,
                log_m,
                log_n,
            },
        )?;

        // ── IOR 3: Bridge — publish (td_new, η, ν₀); split z ─────────
        let BridgeProverOutput {
            reduced:
                BridgeReduced {
                    eta,
                    nu_0,
                    td_new_root: _,
                },
            carry: BridgeProverCarry { td_new, new_x, new_w },
        } = bridge_ior.prove(
            prover_state,
            BridgeProverInput {
                zeta_0: &zeta_0,
                beta_tau: &beta_tau,
                z: &z,
                f: &f,
                bundled_pesat: &self.params.p,
                hasher: &self.params.hasher,
                code_len: n,
                log_m,
                n_minus_k: N - k,
            },
        )?;

        // ── IOR 4: OOD — query reduced oracle out of domain ──────────
        let OodProverOutput {
            reduced: OodReduced { samples_flat, answers },
            carry: (),
        } = ood_ior.prove(
            prover_state,
            OodProverInput {
                oracle: &f,
                s: self.params.config.s,
                log_n,
            },
        )?;

        // ── IOR 5: SampleQueries — sample t shift positions ──────────
        let SampleQueriesProverOutput {
            reduced: SampleQueriesReduced { queries },
            carry: (),
        } = sample_queries_ior.prove(
            prover_state,
            SampleQueriesProverInput {
                log_n,
                t: self.params.config.t,
            },
        )?;

        // ── IOR 6: Batching — DAG fan-in over (ζ₀, OOD, queries) ─────
        let BatchingProverOutput {
            reduced: BatchingReduced { alpha },
            carry: BatchingProverCarry { mu },
        } = batching_ior.prove(
            prover_state,
            BatchingProverInput {
                zeta_0: &zeta_0,
                samples_flat: &samples_flat,
                query_eval_points: &queries.evaluation_points,
                oracle: &f,
                s: self.params.config.s,
                t: self.params.config.t,
                log_n,
            },
        )?;

        // ── IOR 7: Proximity — open committed oracles at shift positions ──
        let ProximityProverOutput {
            reduced: (),
            carry: (),
            proof: ProximityProof {
                auth_0,
                auth_j,
                shift_query_answers,
            },
        } = proximity_ior.prove(
            prover_state,
            ProximityProverInput {
                queries: &queries,
                td_0: &td_0,
                acc_td: &acc_tds,
                l2,
                t: self.params.config.t,
                n,
            },
        )?;

        // ── Assemble new accumulator state and proof ─────────────────
        let mut nus = Vec::with_capacity(1 + self.params.config.s);
        nus.push(nu_0);
        nus.extend(answers);

        let new_acc_instance = AccumulatorInstance {
            rt: vec![td_new.root().clone()],
            alpha: vec![alpha],
            mu: vec![mu],
            beta: (vec![beta_tau], vec![new_x]),
            eta: vec![eta],
        };
        let new_acc_witness = AccumulatorWitness {
            td: vec![td_new],
            w: vec![new_w],
        };
        let proof = WARPProof {
            rt_0: td_0.root().clone(),
            mu_i: mus,
            nu_0,
            nu_i: nus,
            auth_0,
            auth_j,
            shift_query_answers,
        };

        Ok(((new_acc_instance, new_acc_witness), proof))
    }

    fn verify<'a>(
        &self,
        vk: Self::VerifierKey,
        verifier_state: &mut VerifierState<'a>,
        acc_instance: AccumulatorInstance<F, H>,
        proof: WARPProof<F, H>,
    ) -> Result<(), VerifierError> {
        let (l1, l) = (self.params.config.l1, self.params.config.l);
        let l2 = l - l1;

        #[allow(non_snake_case)]
        let (M, N, k) = (vk.m, vk.n, vk.k);
        let (log_m, log_l) = (log2(M) as usize, log2(l) as usize);
        let n = self.params.code.code_len();
        let log_n = log2(n) as usize;

        // Parse the transcript-side statement (l1 fresh instances + l2
        // accumulated entries). Stays in the orchestrator: it crosses
        // the pipeline/non-pipeline boundary by definition.
        let (l1_xs, parsed_acc) =
            parse_statement::<F, H>(verifier_state, l1, l2, N - k, log_n, log_m)?;

        // Cache prior-accumulator values needed by the post-pipeline
        // (α, β) consistency checks. These cross-reference the prior
        // single-entry `acc_instance` against the pipeline's reduced
        // outputs, so they live outside the pipeline.
        let acc_alpha_first = acc_instance.alpha[0].clone();
        let acc_beta_0_first = acc_instance.beta.0[0].clone();
        let acc_beta_1_first = acc_instance.beta.1[0].clone();
        let acc_mu_first = acc_instance.mu[0];
        let l2_taus = parsed_acc.beta.0.clone();
        let l2_xs = parsed_acc.beta.1.clone();

        // Cache the accumulated roots before `parsed_acc` moves into TC's
        // statement — Proximity needs them for the per-acc Merkle handles.
        let l2_roots = parsed_acc.rt.clone();

        // IOR instances.
        let pesat_ior = Pesat::<F, C, H> {
            code: &self.params.code,
            hasher: &self.params.hasher,
            _phantom: PhantomData,
        };
        let twin_constraint_ior = TwinConstraint::<F, H> {
            r1cs: self.params.p.constraints(),
            _phantom: PhantomData,
        };
        let bridge_ior = Bridge::<F, P, H>::new();
        let ood_ior = Ood::<F>::new();
        let sample_queries_ior = SampleQueries::<F>::new();
        let batching_ior = Batching::<F>::new();
        let proximity_ior = Proximity::<F, H> {
            hasher: &self.params.hasher,
            _phantom: PhantomData,
        };

        // ── IOR 1: PESAT — read commitment and (μ, τ) ────────────────
        let PesatVerifierOutput {
            reduced: PesatReduced {
                mus: l1_mus,
                taus: l1_taus,
            },
            carry: PesatVerifierCarry { rt_0 },
        } = pesat_ior.verify(verifier_state, PesatVerifierInput { l1, log_m })?;

        // ── IOR 2: TwinConstraint::verify ────────────────────────────
        let TwinConstraintVerifierOutput {
            reduced:
                TwinConstraintReduced {
                    gamma,
                    zeta_0,
                    beta_tau: _,
                    deferred,
                },
            carry: (),
        } = twin_constraint_ior.verify(
            verifier_state,
            TwinConstraintVerifierInput {
                parsed_acc,
                l1_mus: &l1_mus,
                l1_taus: &l1_taus,
                log_l,
                log_m,
                log_n,
            },
        )?;

        // ── IOR 3: Bridge — read (td, η, ν₀); discharge TC's deferred ─
        let BridgeVerifierOutput {
            reduced: BridgeReduced {
                eta: _,
                nu_0,
                td_new_root: _,
            },
            carry: (),
        } = bridge_ior.verify(
            verifier_state,
            BridgeVerifierInput {
                gamma: &gamma,
                deferred: &deferred,
            },
        )?;

        // ── IOR 4: OOD::verify ──────────────────────────────────────
        let OodVerifierOutput {
            reduced: OodReduced { samples_flat, answers },
            carry: (),
        } = ood_ior.verify(
            verifier_state,
            OodVerifierInput {
                s: self.params.config.s,
                log_n,
            },
        )?;

        // ── IOR 5: SampleQueries::verify ────────────────────────────
        let SampleQueriesVerifierOutput {
            reduced: SampleQueriesReduced { queries },
            carry: (),
        } = sample_queries_ior.verify(
            verifier_state,
            SampleQueriesVerifierInput {
                log_n,
                t: self.params.config.t,
            },
        )?;

        // ── IOR 7: Proximity::verify (arity + handle building lives here) ──
        let ProximityVerifierOutput { reduced: (), carry: () } = proximity_ior.verify(
            verifier_state,
            ProximityVerifierInput {
                queries: &queries,
                rt_0: &rt_0,
                l2_roots: &l2_roots,
                auth_0: &proof.auth_0,
                auth_j: &proof.auth_j,
                shift_query_answers: &proof.shift_query_answers,
                l2,
                t: self.params.config.t,
                n,
            },
        )?;

        // ── Recompute ν vector from shift answers (orchestrator-owned) ──
        let gamma_eq_evals = compute_hypercube_eq_evals(log_l, &gamma);
        let mut nus = Vec::with_capacity(1 + self.params.config.s + self.params.config.t);
        nus.push(nu_0);
        nus.extend(answers);
        for v_jk in proof.shift_query_answers.iter() {
            let nu_st = v_jk
                .iter()
                .zip(&gamma_eq_evals)
                .fold(F::zero(), |acc, (v, eq)| acc + *eq * *v);
            nus.push(nu_st);
        }

        // ── IOR 6: Batching::verify ─────────────────────────────────
        let BatchingVerifierOutput {
            reduced: BatchingReduced { alpha },
            carry: (),
        } = batching_ior.verify(
            verifier_state,
            BatchingVerifierInput {
                zeta_0: &zeta_0,
                samples_flat: &samples_flat,
                query_eval_points: &queries.evaluation_points,
                nus,
                acc_mu: acc_mu_first,
                s: self.params.config.s,
                t: self.params.config.t,
                log_n,
            },
        )?;

        // ── Post-pipeline accumulator consistency ──────────────────
        (acc_alpha_first == alpha)
            .then_some(())
            .ok_or(VerifierError::CodeEvaluationPoint)?;

        let betas = l2_taus
            .into_iter()
            .chain(l1_taus)
            .zip(l2_xs.into_iter().chain(l1_xs))
            .map(|(tau_i, x)| concat_slices(&tau_i, &x))
            .collect::<Vec<Vec<F>>>();
        let beta = scale_and_sum(&betas, &gamma_eq_evals);
        let expected_beta = concat_slices(&acc_beta_0_first, &acc_beta_1_first);
        (expected_beta == beta)
            .then_some(())
            .ok_or(VerifierError::CircuitEvaluationPoint)?;

        Ok(())
    }

    fn decide(
        &self,
        acc_witness: AccumulatorWitness<F, H>,
        acc_instance: AccumulatorInstance<F, H>,
    ) -> Result<(), WARPError> {
        // The accumulator witness's codeword is td[0].codewords()[0].
        let acc_codeword = &acc_witness.td[0].codewords()[0];

        // Re-encode the witness; check codeword match.
        let computed_f = self.params.code.encode(&acc_witness.w[0]);
        (acc_codeword == &computed_f).then_some(()).ok_or(DeciderError::EncodedWitness)?;

        // Re-commit and check root.
        let scheme = warp_scheme::<H, F>(self.params.hasher.clone(), self.params.code.code_len());
        let recomputed = scheme.commit(std::slice::from_ref(&computed_f));
        (acc_instance.rt[0] == *recomputed.root()).then_some(()).ok_or(DeciderError::MerkleRoot)?;
        (acc_witness.td[0].root() == recomputed.root()).then_some(()).ok_or(DeciderError::MerkleTrapDoor)?;

        // MLE evaluation check.
        let f_hat = DenseMultilinearExtension::from_evaluations_slice(
            log2(self.params.code.code_len()) as usize,
            acc_codeword,
        );
        (f_hat.evaluate(&acc_instance.alpha[0]) == acc_instance.mu[0])
            .then_some(()).ok_or(DeciderError::MLExtensionEvaluation)?;

        // Bundled-evaluation check.
        let tau = &acc_instance.beta.0[0];
        let tau_zero_evader = compute_hypercube_eq_evals(tau.len(), tau);
        let mut z = acc_instance.beta.1[0].clone();
        z.extend(acc_witness.w[0].clone());
        let computed_eta = self
            .params
            .p
            .evaluate_bundled(&tau_zero_evader, &z)
            .unwrap();
        (computed_eta == acc_instance.eta[0]).then_some(()).ok_or(DeciderError::BundledEvaluation)?;

        Ok(())
    }
}
