#![allow(clippy::assign_op_pattern)] // generated by SmallFpConfig derive macro
use crate::error::WARPError;
use crate::traits::AccumulationScheme;
use crate::types::{AccumulatorInstance, AccumulatorWitness, ProveResult, WARPParams, WARPProof};
use ark_codes::traits::LinearCode;
use ark_ff::{Field, PrimeField};
use ark_mt::MerkleHasher;
use ark_poly::{DenseMultilinearExtension, Polynomial};
use ark_std::log2;
use config::WARPConfig;
use effsc::hypercube::{compute_hypercube_eq_evals, Ascending};
use protocol::query::QueryIndices;
use protocol::transcript::{absorb_instances, parse_statement};
use relations::{r1cs::R1CSConstraints, BundledPESAT};
use spongefish::{Decoding, Encoding, NargDeserialize, NargSerialize, ProverState, VerifierState};
use std::marker::PhantomData;
use utils::scale_and_sum;
use utils::{concat_slices, poly::eq_poly};

pub mod config;
pub mod constraints;
pub mod crypto;
pub mod error;
pub mod params;
pub mod profile;
pub mod protocol;
pub mod relations;
pub mod serialize;
pub mod traits;
pub mod types;
pub mod utils;

use crate::crypto::merkle::warp_scheme;
use error::{DeciderError, ProverError, VerifierError};
use protocol::phases::{
    batching::{Batching, BatchingProverInputs, BatchingStatement, BatchingVerifierInputs},
    ood::{Ood, OodProverInputs, OodStatement},
    oracle_handle::{IndexedOracle, MerkleIndexedOracle},
    pesat::{Pesat, PesatStatement, PesatWitness},
    proximity::{Proximity, ProximityProverInputs, ProximityStatement, ProximityVerifierInputs},
    twin_constraint::{
        TwinConstraint, TwinConstraintProverInputs, TwinConstraintStatement, TwinConstraintWitness,
    },
    IOR,
};

pub trait BoolResult {
    fn ok_or_err<E>(self, err: E) -> Result<(), E>;
}

impl BoolResult for bool {
    #[inline]
    fn ok_or_err<E>(self, err: E) -> Result<(), E> {
        if self {
            Ok(())
        } else {
            Err(err)
        }
    }
}

pub struct WARP<F: Field, P: BundledPESAT<F>, C: LinearCode<F> + Clone, H: MerkleHasher> {
    pub params: WARPParams<F, P, C, H>,
}

impl<F, P, C, H> WARP<F, P, C, H>
where
    F: Field,
    P: Clone + BundledPESAT<F, Config = (usize, usize, usize)>,
    C: LinearCode<F> + Clone,
    H: MerkleHasher<Symbol = Vec<F>>,
{
    pub fn new(config: WARPConfig<F, P>, code: C, p: P, hasher: H) -> WARP<F, P, C, H> {
        Self {
            params: WARPParams {
                _f: PhantomData,
                config,
                code,
                p,
                hasher,
            },
        }
    }
}

impl<F, P, C, H> AccumulationScheme<F, H> for WARP<F, P, C, H>
where
    F: Field + PrimeField + Encoding<[u8]> + Decoding<[u8]> + NargDeserialize + NargSerialize,
    P: Clone + BundledPESAT<F, Constraints = R1CSConstraints<F>, Config = (usize, usize, usize)>,
    C: LinearCode<F> + Clone,
    H: MerkleHasher<Symbol = Vec<F>>,
    H::Digest: Encoding<[u8]> + Decoding<[u8]> + NargSerialize + NargDeserialize + Clone + Eq,
{
    type Index = P;
    type ProverKey = (P, usize, usize, usize);
    type VerifierKey = (usize, usize, usize);
    type Instances = Vec<Vec<F>>;
    type Witnesses = Vec<Vec<F>>;

    fn index(
        prover_state: &mut ProverState,
        index: Self::Index,
    ) -> spongefish::VerificationResult<(Self::ProverKey, Self::VerifierKey)> {
        let (m, n, k) = index.config();
        prover_state.public_message(&index.description());
        prover_state.prover_message(&F::from(m as u32));
        prover_state.prover_message(&F::from(n as u32));
        prover_state.prover_message(&F::from(k as u32));
        Ok(((index, m, n, k), (m, n, k)))
    }

    #[tracing::instrument(name = "warp.prove", skip_all)]
    fn prove(
        &self,
        pk: Self::ProverKey,
        prover_state: &mut ProverState,
        witnesses: Self::Witnesses,
        instances: Self::Instances,
        acc_instance: AccumulatorInstance<F, H>,
        acc_witness: AccumulatorWitness<F, H>,
    ) -> ProveResult<F, H> {
        debug_assert!(instances.len() > 1);
        debug_assert_eq!(witnesses.len(), instances.len());
        debug_assert_eq!(acc_witness.td.len(), acc_instance.rt.len());

        let (l1, l) = (self.params.config.l1, self.params.config.l);
        let l2 = l - l1;
        debug_assert_eq!(l1 + l2, l);
        debug_assert!(l.is_power_of_two());

        #[allow(non_snake_case)]
        let (M, N, k) = (pk.1, pk.2, pk.3);
        let (log_m, log_l) = (log2(M) as usize, log2(l) as usize);
        let n = self.params.code.code_len();
        let log_n = log2(n) as usize;

        debug_assert_eq!(instances[0].len(), N - k);
        absorb_instances(prover_state, &instances);
        acc_instance.absorb_into(prover_state);

        // Destructure acc_witness. Codewords live inside td[i].codewords();
        // we extract the single codeword per accumulator entry into acc_fs
        // for use by twin_constraint.
        let AccumulatorWitness {
            td: acc_tds,
            w: acc_ws,
        } = acc_witness;
        let acc_fs: Vec<Vec<F>> = acc_tds.iter().map(|td| td.codewords()[0].clone()).collect();

        // Phase 2: PESAT
        let pesat_phase = Pesat::<F, C, H> {
            code: &self.params.code,
            hasher: &self.params.hasher,
            _phantom: PhantomData,
        };
        let (pesat_red, _pesat_proof, pesat_red_wit) = pesat_phase.prove(
            prover_state,
            &PesatStatement { l1, log_m },
            &PesatWitness {
                witnesses: &witnesses,
            },
            &(),
        )?;

        // Phase 3a: twin-constraint sumcheck
        let tc_phase = TwinConstraint::<F, H> {
            r1cs: self.params.p.constraints(),
            _phantom: PhantomData,
        };
        let (tc_red, _tc_proof, tc_red_wit) = tc_phase.prove(
            prover_state,
            &TwinConstraintStatement {
                acc_instance,
                l1_mus: pesat_red.mus.clone(),
                l1_taus: pesat_red.taus,
                log_l,
                log_m,
                log_n,
            },
            &TwinConstraintWitness {
                acc_witness_w: &acc_ws,
                instances: &instances,
                witnesses: &witnesses,
            },
            &TwinConstraintProverInputs {
                fresh_codewords: &pesat_red_wit.codewords,
                acc_codewords: &acc_fs,
            },
        )?;

        // Phase 3b: bundled η, ν₀, new commitment, absorb.
        let beta_eq_evals = (0..M)
            .map(|i| eq_poly(&tc_red.beta_tau, i))
            .collect::<Vec<_>>();
        let eta = self
            .params
            .p
            .evaluate_bundled(&beta_eq_evals, &tc_red_wit.z)
            .map_err(|_| ProverError::SpongeFish)?;
        let nu_0 = tc_red_wit.f.query_at_point(&tc_red.zeta_0);

        let (new_x, new_w) = tc_red_wit.z.split_at(N - k);
        let new_x = new_x.to_vec();
        let new_w = new_w.to_vec();
        let new_beta = (vec![tc_red.beta_tau.clone()], vec![new_x]);

        // Commit to the new (single-codeword) reduced oracle.
        let td_new = {
            let _s = tracing::info_span!("warp.commit_new_oracle").entered();
            count_ops!(MerkleTreeBuilds);
            let scheme = warp_scheme::<H, F>(self.params.hasher.clone(), n);
            let new_codeword = tc_red_wit.f.evals().to_vec();
            scheme.commit(&[new_codeword])
        };
        prover_state.prover_message(td_new.root());
        prover_state.prover_message(&eta);
        prover_state.prover_message(&nu_0);

        // Phase 3c: OOD
        let ood_phase = Ood::<F>::new();
        let (ood_red, _, _) = ood_phase.prove(
            prover_state,
            &OodStatement {
                s: self.params.config.s,
                log_n,
            },
            &(),
            &OodProverInputs {
                oracle: &tc_red_wit.f,
            },
        )?;

        // Sample shift queries.
        let queries = QueryIndices::<F>::sample(prover_state, log_n, self.params.config.t);

        // Phase 3d: batching sumcheck.
        let mut zetas: Vec<Vec<F>> =
            Vec::with_capacity(1 + self.params.config.s + self.params.config.t);
        zetas.push(tc_red.zeta_0.clone());
        for chunk in ood_red.samples_flat.chunks(log_n) {
            zetas.push(chunk.to_vec());
        }
        for q in &queries.evaluation_points {
            zetas.push(q.clone());
        }

        let batching_phase = Batching::<F>::new();
        let (batching_red, _, batching_red_wit) = batching_phase.prove(
            prover_state,
            &BatchingStatement {
                zetas_prefix: zetas,
                s: self.params.config.s,
                t: self.params.config.t,
                log_n,
                _phantom: PhantomData,
            },
            &(),
            &BatchingProverInputs {
                oracle: &tc_red_wit.f,
            },
        )?;

        // Phase 3e: proximity.
        let proximity_phase = Proximity::<F, H> {
            hasher: &self.params.hasher,
            _phantom: PhantomData,
        };
        let (_, prox, _) = proximity_phase.prove(
            prover_state,
            &ProximityStatement {
                queries: queries.clone(),
                l2,
                t: self.params.config.t,
                n,
            },
            &(),
            &ProximityProverInputs {
                td_0: &pesat_red_wit.td_0,
                acc_td: &acc_tds,
            },
        )?;

        // Assemble new accumulator state and proof.
        let mut nus = Vec::with_capacity(1 + self.params.config.s);
        nus.push(nu_0);
        nus.extend(ood_red.answers);

        let new_acc_instance = AccumulatorInstance {
            rt: vec![td_new.root().clone()],
            alpha: vec![batching_red.alpha],
            mu: vec![batching_red_wit.mu],
            beta: new_beta,
            eta: vec![eta],
        };
        let new_acc_witness = AccumulatorWitness {
            td: vec![td_new],
            w: vec![new_w],
        };
        let proof = WARPProof {
            rt_0: pesat_red_wit.td_0.root().clone(),
            mu_i: pesat_red.mus,
            nu_0,
            nu_i: nus,
            auth_0: prox.auth_0,
            auth_j: prox.auth_j,
            shift_query_answers: prox.shift_query_answers,
        };

        Ok(((new_acc_instance, new_acc_witness), proof))
    }

    fn verify<'a>(
        &self,
        vk: Self::VerifierKey,
        verifier_state: &mut VerifierState<'a>,
        acc_instance: AccumulatorInstance<F, H>,
        proof: WARPProof<F, H>,
    ) -> Result<(), VerifierError> {
        let (l1, l) = (self.params.config.l1, self.params.config.l);
        let l2 = l - l1;

        #[allow(non_snake_case)]
        let (M, N, k) = (vk.0, vk.1, vk.2);
        let (log_m, log_l) = (log2(M) as usize, log2(l) as usize);
        let n = self.params.code.code_len();
        let log_n = log2(n) as usize;

        // 1. Parse statement
        let (l1_xs, parsed_acc) =
            parse_statement::<F, H>(verifier_state, l1, l2, N - k, log_n, log_m)?;
        let acc_alpha_first = acc_instance.alpha[0].clone();
        let acc_beta_0_first = acc_instance.beta.0[0].clone();
        let acc_beta_1_first = acc_instance.beta.1[0].clone();
        let acc_mu_first = acc_instance.mu[0];
        let l2_roots = parsed_acc.rt.clone();
        let l2_taus = parsed_acc.beta.0.clone();
        let l2_xs = parsed_acc.beta.1.clone();

        // 2. PESAT::verify
        let pesat_phase = Pesat::<F, C, H> {
            code: &self.params.code,
            hasher: &self.params.hasher,
            _phantom: PhantomData,
        };
        let (pesat_red, pesat_v_out) =
            pesat_phase.verify(verifier_state, &PesatStatement { l1, log_m }, &())?;
        let l1_mus = pesat_red.mus;
        let l1_taus = pesat_red.taus;
        let rt_0 = pesat_v_out.rt_0;

        // 3. TwinConstraint::verify
        let tc_phase = TwinConstraint::<F, H> {
            r1cs: self.params.p.constraints(),
            _phantom: PhantomData,
        };
        let (tc_red, _) = tc_phase.verify(
            verifier_state,
            &TwinConstraintStatement {
                acc_instance: parsed_acc,
                l1_mus,
                l1_taus: l1_taus.clone(),
                log_l,
                log_m,
                log_n,
            },
            &(),
        )?;

        // 4. Read between TC and OOD: td (new commitment), η, ν₀.
        let _td_digest: H::Digest = verifier_state.prover_message()?;
        let eta: F = verifier_state.prover_message()?;
        let nu_0: F = verifier_state.prover_message()?;

        // 5. Discharge the deferred oracle check.
        tc_red.deferred.discharge(&tc_red.gamma, nu_0, eta)?;

        // 6. OOD::verify
        let ood_phase = Ood::<F>::new();
        let (ood_red, _) = ood_phase.verify(
            verifier_state,
            &OodStatement {
                s: self.params.config.s,
                log_n,
            },
            &(),
        )?;

        // 7. Squeeze shift-query bytes; build queries; Proximity::verify.
        let n_shift_query_bytes = (self.params.config.t * log_n).div_ceil(8);
        let bytes_shift_queries: Vec<u8> = (0..n_shift_query_bytes)
            .map(|_| verifier_state.verifier_message::<[u8; 1]>()[0])
            .collect();
        let queries: QueryIndices<F> =
            QueryIndices::from_squeezed_bytes(&bytes_shift_queries, log_n, self.params.config.t);

        // Arity checks on the proof's shape. The orchestrator owns these
        // since they're whole-proof shape checks, not per-oracle opening
        // validity (which lives behind the IndexedOracle handles).
        (proof.shift_query_answers.len() == self.params.config.t)
            .ok_or_err(VerifierError::NumShiftQueries)?;
        (proof.auth_j.len() == l2).ok_or_err(VerifierError::NumL2Instances)?;

        // Build (sorted, unique) leaf positions and a map from each unique
        // position to a row in shift_query_answers (duplicates land on the
        // same row).
        let mut indexed: Vec<(usize, usize)> = queries
            .leaf_positions
            .iter()
            .copied()
            .enumerate()
            .map(|(row, pos)| (pos, row))
            .collect();
        indexed.sort_by_key(|&(pos, _)| pos);
        indexed.dedup_by_key(|&mut (pos, _)| pos);
        let sorted_unique: Vec<usize> = indexed.iter().map(|&(p, _)| p).collect();
        let row_indices: Vec<usize> = indexed.iter().map(|&(_, r)| r).collect();

        // Construct the BCS-checked oracle handles. The Proximity phase
        // itself stays BCS-agnostic — it only sees `&dyn IndexedOracle`.
        // Each handle gets its own `WarpScheme` built from the hasher value.
        let fresh_values: Vec<Vec<F>> = row_indices
            .iter()
            .map(|&r| proof.shift_query_answers[r][l2..].to_vec())
            .collect();
        let fresh_handle = MerkleIndexedOracle::new(
            warp_scheme::<H, F>(self.params.hasher.clone(), n),
            &rt_0,
            &proof.auth_0,
            sorted_unique.clone(),
            fresh_values,
        );

        let acc_handles: Vec<MerkleIndexedOracle<F, H>> = (0..l2)
            .map(|k| {
                let acc_values: Vec<Vec<F>> = row_indices
                    .iter()
                    .map(|&r| vec![proof.shift_query_answers[r][k]])
                    .collect();
                MerkleIndexedOracle::new(
                    warp_scheme::<H, F>(self.params.hasher.clone(), n),
                    &l2_roots[k],
                    &proof.auth_j[k],
                    sorted_unique.clone(),
                    acc_values,
                )
            })
            .collect();
        let acc_refs: Vec<&dyn IndexedOracle<Vec<F>>> = acc_handles
            .iter()
            .map(|h| h as &dyn IndexedOracle<Vec<F>>)
            .collect();

        let proximity_phase = Proximity::<F, H> {
            hasher: &self.params.hasher,
            _phantom: PhantomData,
        };
        proximity_phase.verify(
            verifier_state,
            &ProximityStatement {
                queries: queries.clone(),
                l2,
                t: self.params.config.t,
                n,
            },
            &ProximityVerifierInputs {
                fresh: &fresh_handle,
                acc: &acc_refs,
                _h: PhantomData,
            },
        )?;

        // 8. Compute ν_{s+k} from shift answers; assemble nus.
        let gamma_eq_evals = compute_hypercube_eq_evals(log_l, &tc_red.gamma);
        let mut nus = Vec::with_capacity(1 + self.params.config.s + self.params.config.t);
        nus.push(nu_0);
        nus.extend(ood_red.answers);
        for v_jk in proof.shift_query_answers.iter() {
            let nu_st = v_jk
                .iter()
                .zip(&gamma_eq_evals)
                .fold(F::zero(), |acc, (v, eq)| acc + *eq * *v);
            nus.push(nu_st);
        }

        // 9. Build zetas_prefix; Batching::verify.
        let mut zetas: Vec<Vec<F>> =
            Vec::with_capacity(1 + self.params.config.s + self.params.config.t);
        zetas.push(tc_red.zeta_0.clone());
        for chunk in ood_red.samples_flat.chunks(log_n) {
            zetas.push(chunk.to_vec());
        }
        for pt in &queries.evaluation_points {
            zetas.push(pt.clone());
        }

        let batching_phase = Batching::<F>::new();
        let (batching_red, _) = batching_phase.verify(
            verifier_state,
            &BatchingStatement {
                zetas_prefix: zetas,
                s: self.params.config.s,
                t: self.params.config.t,
                log_n,
                _phantom: PhantomData,
            },
            &BatchingVerifierInputs {
                nus,
                acc_mu: acc_mu_first,
            },
        )?;

        // 10. Accumulator consistency.
        (acc_alpha_first == batching_red.alpha).ok_or_err(VerifierError::CodeEvaluationPoint)?;

        let betas = l2_taus
            .into_iter()
            .chain(l1_taus)
            .zip(l2_xs.into_iter().chain(l1_xs))
            .map(|(tau_i, x)| concat_slices(&tau_i, &x))
            .collect::<Vec<Vec<F>>>();
        let beta = scale_and_sum(&betas, &gamma_eq_evals);
        let expected_beta = concat_slices(&acc_beta_0_first, &acc_beta_1_first);
        (expected_beta == beta).ok_or_err(VerifierError::CircuitEvaluationPoint)?;

        Ok(())
    }

    fn decide(
        &self,
        acc_witness: AccumulatorWitness<F, H>,
        acc_instance: AccumulatorInstance<F, H>,
    ) -> Result<(), WARPError> {
        // The accumulator witness's codeword is td[0].codewords()[0].
        let acc_codeword = &acc_witness.td[0].codewords()[0];

        // Re-encode the witness; check codeword match.
        let computed_f = self.params.code.encode(&acc_witness.w[0]);
        (acc_codeword == &computed_f).ok_or_err(DeciderError::EncodedWitness)?;

        // Re-commit and check root.
        let scheme = warp_scheme::<H, F>(self.params.hasher.clone(), self.params.code.code_len());
        let recomputed = scheme.commit(std::slice::from_ref(&computed_f));
        (acc_instance.rt[0] == *recomputed.root()).ok_or_err(DeciderError::MerkleRoot)?;
        (acc_witness.td[0].root() == recomputed.root()).ok_or_err(DeciderError::MerkleTrapDoor)?;

        // MLE evaluation check.
        let f_hat = DenseMultilinearExtension::from_evaluations_slice(
            log2(self.params.code.code_len()) as usize,
            acc_codeword,
        );
        (f_hat.evaluate(&acc_instance.alpha[0]) == acc_instance.mu[0])
            .ok_or_err(DeciderError::MLExtensionEvaluation)?;

        // Bundled-evaluation check.
        let tau = &acc_instance.beta.0[0];
        let tau_zero_evader = Ascending::new(tau.len())
            .map(|p| eq_poly(tau, p.index))
            .collect::<Vec<F>>();
        let mut z = acc_instance.beta.1[0].clone();
        z.extend(acc_witness.w[0].clone());
        let computed_eta = self
            .params
            .p
            .evaluate_bundled(&tau_zero_evader, &z)
            .unwrap();
        (computed_eta == acc_instance.eta[0]).ok_or_err(DeciderError::BundledEvaluation)?;

        Ok(())
    }
}
